title:             Stacy Montemayor
email:             stacy.montemayor@gmail.com
description:       Research | Data Wrangling + Visualizations
author:            Stacy Montemayor
baseurl:           ""
url:               "https://teacupwoozy.github.io"

google_analytics: UA-134703235-1

# Social Profiles
twitter_username:  teacupwoozy
github_username:   teacupwoozy
linkedin_username: stacymontemayor
# facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
